"""extend users schema with first_name, last_name, phone_number

Revision ID: 240cb7e2123a
Revises: 5c0a7c037986
Create Date: 2026-07-21 16:32:55.753239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '240cb7e2123a'
down_revision: Union[str, None] = '5c0a7c037986'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Добавляем колонки БЕЗ NOT NULL
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))

    # 2. Заполняем СУЩЕСТВУЮЩИЕ строки временным значением
    op.execute("UPDATE users SET first_name = 'Не указано' WHERE first_name IS NULL")
    op.execute("UPDATE users SET last_name = 'Не указано' WHERE last_name IS NULL")
    op.execute("UPDATE users SET phone_number = '+0000000' || id WHERE phone_number IS NULL")

    # 3. Теперь делаем поля обязательными
    op.alter_column('users', 'first_name', nullable=False)
    op.alter_column('users', 'last_name', nullable=False)
    op.alter_column('users', 'phone_number', nullable=False)

    # 4. задаем имена для уникальных значений
    op.create_unique_constraint('uq_users_email', 'users', ['email'])
    op.create_unique_constraint('uq_users_phone_number', 'users', ['phone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_users_email', 'users', type_='unique')
    op.drop_constraint('uq_users_phone_number', 'users', type_='unique')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
