"""create roles table

Revision ID: 3213644d0b49
Revises: 240cb7e2123a
Create Date: 2026-07-21 21:53:01.048651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3213644d0b49'
down_revision: Union[str, None] = '240cb7e2123a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'roles',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )

    # Заполняем таблицу roles ДО того, как на неё будет ссылаться внешний ключ
    roles_table = sa.table(
        'roles',
        sa.column('id', sa.Integer),
        sa.column('name', sa.String),
    )
    op.bulk_insert(
        roles_table,
        [
            {'id': 1, 'name': 'user'},
            {'id': 2, 'name': 'admin'},
        ]
    )

    op.add_column('users', sa.Column('role_id', sa.Integer(), server_default='1', nullable=False))
    op.create_foreign_key('fk_users_role_id_roles', 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_role_id_roles', 'users', type_='foreignkey')
    op.drop_column('users', 'role_id')
    op.drop_table('roles')
    # ### end Alembic commands ###
